<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Order #<?= esc($order->id) ?></title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .table th, .table td { border: 1px solid #ddd; padding: 6px; }
        .table th { background: #f2f2f2; }
        .totals { margin-top: 20px; text-align: right; }
        .footer { margin-top: 30px; font-size: 11px; text-align: right; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <img class="qr-code" src="https://nairobimetaldetectors.net/logo.png" alt="www.nairobimetaldetectors.net" height="60"><br>
        <h2><?= esc($company->name ?? 'Company') ?></h2>
        <p><?= esc($company->address ?? '') ?> | <?= esc($company->phone ?? '') ?></p>
        <p><?= esc($company->email) ?></p>
    </div>

    <h3>Order #<?= esc($order->id) ?></h3>
    <?php
        // Convert order created_at
        $orderDate = \CodeIgniter\I18n\Time::parse($order->created_at)
                        ->setTimezone('Africa/Nairobi')
                        ->toLocalizedString('dd MMM yyyy HH:mm:ss');

        // Current generated time
        $generatedDate = \CodeIgniter\I18n\Time::now('Africa/Nairobi')
                        ->toLocalizedString('dd MMM yyyy HH:mm:ss');
    ?>
    <p><strong>Order Date:</strong> <?= $orderDate ?></p>
    <p><strong>Generated On:</strong> <?= $generatedDate ?></p>

    <?php if (!empty($order->customer_name)): ?>
        <h4>Customer Details</h4>
        <p>
            <strong>Name:</strong> <?= esc($order->customer_name) ?> |
            <strong>Email:</strong> <?= esc($order->customer_email) ?> |
            <strong>Phone:</strong> <?= esc($order->customer_phone) ?>
        </p>
        <p><strong>Address:</strong> <?= esc($order->customer_address) ?></p>
    <?php endif; ?>

    <h4>Items</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Item</th>
                <th>Qty</th>
                <th>Price</th>
                <th>Total</th>
                <th>Cashier</th>
            </tr>
        </thead>
        <tbody>
        <?php $grandTotal = 0; $totalItems = 0; ?>
        <?php foreach ($items as $item): ?>
            <?php
                $lineTotal = $item->sellingPrice * $item->quantity;
                $grandTotal += $lineTotal;
                $totalItems += $item->quantity;
            ?>
            <tr>
                <td><?= esc($item->item_name) ?></td>
                <td><?= esc($item->quantity) ?></td>
                <td><?= number_format($item->sellingPrice, 2) ?></td>
                <td><?= number_format($lineTotal, 2) ?></td>
                <td><?= esc($item->cashier) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <div class="totals">
        <p><strong>Total Items:</strong> <?= $totalItems ?></p>
        <p><strong>Grand Total:</strong> Kshs <?= number_format($grandTotal, 2) ?></p>
    </div>

    <div class="footer">
        <p>Generated by <?= esc($company->name ?? 'System') ?> | <?= $generatedDate ?> (Africa/Nairobi)</p>
    </div>
</body>
</html>
